name = "hasmariahcareybreachedcontainment"
compatibility_date = "2022-11-15"
workers_dev = true
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build && worker-build --release" # required
